const menuPrices = {
    "Chilaquiles": 80,
    "Enchiladas": 90,
    "Quesadillas": 50,
    "Tamal de rajas": 25,
    "Tamal de rojo": 25,
    "Tamal de elote": 30,
    "Conchas": 20,
    "Churros": 25,
    "Arroz con leche": 15,
    "Pan de muerto": 35,
    "Capirotada": 40,
    "Nieve": 30,
    "Café de olla": 35,
    "Chocolate Caliente": 40,
    "Horchata": 25,
    "Aguas frescas": 20,
    "Té de manzanilla": 15,
    "Champurrado": 35,
};
